name: Multiplication Table

on:
 workflow_dispatch:
#  push:
#    branches:
#      - main  # Change this to any branch you want to trigger on

jobs:
  evaluate-odd-numbers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (if needed, optional for this task)
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Execute a script to display odd numbers, skipping 9
      - name: Display Odd Numbers and Skip 9
        run: |
          #!/bin/bash
          echo " Printing table of" $num 
          num=10
          for (( i=0; i<=10; i++))
          do 
            # x=$(( num*i ))  
            # echo "$num x $i = $x"
              echo "$num x $i = " $(( num*i))
          done 
